extend type Query {
  admin: AdminLoginResponse!
}

extend type Mutation {
  adminLogin(input: AdminLoginRequestInput!): AdminLoginResponse!
  adminForgotPassword(input: ForgotPasswordRequestInput!): Response!
  adminVerifyOtpForResetPassword(
    input: VerifyOtpForResetPasswordRequestInput!
  ): Response!
  adminResetPassword(input: ResetPasswordRequestInput!): Response!
  adminChangePassword(input: ChangePasswordRequestInput!): Response!
  adminEditProfile(input: AdminEditProfileRequestInput!): Response!
}

input AdminLoginRequestInput {
  email: String!
  password: String!
}

input AdminEditProfileRequestInput {
  firstName: String!
  lastName: String!
  oldProfileImageUrl: String!
  newProfileImageFile: Upload
}

type AdminLoginResponse {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  image: String!
  createdAt: String!
  updatedAt: String!
  token: String!
}
