scalar Upload

type Mutation {
  login(input: LoginRequestInput!): LoginResponse!
  socialLogin(input: SocialLoginRequestInput!): LoginResponse!
  signup(input: SignUpRequestInput!): Response!
  verifyOtpForSignup(input: VerifyOtpForSignUpRequestInput!): LoginResponse!
  resendOtp(input: ResendOtpRequestInput!): Response!
  forgotPassword(input: ForgotPasswordRequestInput!): Response!
  verifyOtpForResetPassword(
    input: VerifyOtpForResetPasswordRequestInput!
  ): Response!
  resetPassword(input: ResetPasswordRequestInput!): Response!
}

input LoginRequestInput {
  email: String!
  password: String!
}

input SocialLoginRequestInput {
  socialId: String!
  type: String!
  email: String
  name: String!
}

input SignUpRequestInput {
  email: String!
}

input VerifyOtpForSignUpRequestInput {
  name: String!
  email: String!
  password: String!
  otp: String!
}

input ForgotPasswordRequestInput {
  email: String!
}

input VerifyOtpForResetPasswordRequestInput {
  email: String!
  otp: String!
}

input ResetPasswordRequestInput {
  email: String!
  newPassword: String!
  confirmPassword: String!
}

type LoginResponse {
  id: ID!
  name: String!
  email: String!
  image: String!
  createdAt: String!
  updatedAt: String!
  hasPassword: Boolean!
  token: String!
}

type Response {
  message: String!
}

input ResendOtpRequestInput {
  email: String!
}