extend type Mutation {
  category(input: CategoryRequestInput!): Response!
  editCategory(id: ID!, input: EditCategoryRequestInput!): Response!
  deleteCategory(id: ID!): Response!
}

input CategoryRequestInput {
  category: String!
}

input EditCategoryRequestInput {
  category: String!
}

extend type Query {
  getCategories(
    page: Int!
    limit: Int!
    search: String
  ): CategoriesPaginationResponse!
  getCategoryDetail(page: Int!, limit: Int!): CategoryDetailPaginationResponse!
}

type CategoryDetailPaginationResponse {
  total: Int!
  perPage: Int!
  currentPage: Int!
  totalPages: Int!
  category: Category!
}

type CategoriesPaginationResponse {
  total: Int!
  perPage: Int!
  currentPage: Int!
  totalPages: Int!
  categories: [Category!]!
}

type Category {
  id: ID!
  category: String!
}
