type Friend {
  id: ID!
  name: String!
  image: String!
}

type FriendPaginationResponse {
  total: Int!
  perPage: Int!
  currentPage: Int!
  totalPages: Int!
  friends: [Friend!]!
}

type LaughifiUserPaginationResponse {
  total: Int!
  perPage: Int!
  currentPage: Int!
  totalPages: Int!
  users: [Friend!]!
}

extend type Query {
  getFriends(page: Int!, limit: Int!): FriendPaginationResponse!
  getLaughifiUsers(
    page: Int!
    limit: Int!
    search: String
  ): LaughifiUserPaginationResponse!
  getFriendsRequests: [Friend!]!
}

extend type Mutation {
  updateStatus(userId: ID!, input: UpdateStatusRequestInput!): Response!
  sendFriendRequest(input: SendFriendRequestInput!): Response!
}

input UpdateStatusRequestInput {
  Status: String!
}

input SendFriendRequestInput {
  userIds: [ID!]!
}
