extend type Mutation {
  templatePlayWithFriends(
    input: TemplatePlayWithFriendsRequestInput!
  ): Response!
  addAnswer(input: AddAnswerRequestInput!, id: ID!): Response!
}

input TemplatePlayWithFriendsRequestInput {
  friendIds: String!
  templateId: ID!
  answer: [Answer!]!
}

input AddAnswerRequestInput {
  sendAnswerUserId: ID!
  key: String!
  value: String!
}

input Answer {
  key: String!
  value: String!
}

extend type Query {
  getFriendTemplates(
    page: Int!
    limit: Int!
    friendId: String!
  ): FriendTemplatePaginationResponse!
}

type FriendTemplatePaginationResponse {
  total: Int!
  perPage: Int!
  currentPage: Int!
  totalPages: Int!
  friendTemplates: [FriendTemplates!]!
}

type FriendTemplates {
  id: ID!
  template: String!
  category: String!
  title: String!
  answers: [FriendAnswers!]!
}

type FriendAnswers {
  id: ID!
  key: String!
  value: String!
}

type Subscription {
  templateShared: TemplatePlayWithFriend!
}

type TemplatePlayWithFriend {
  id: ID!
  friendId: ID!
  template: String!
  topic: String!
  title: String!
  answers: [TemplateAnswers!]!
  status: String!
}

type TemplateAnswers {
  id: ID!
  key: String!
  value: String!
}
