type Template {
  id: ID!
  title: String!
  topic: String!
  template: String!
}

type TemplatePaginationResponse {
  total: Int!
  perPage: Int!
  currentPage: Int!
  totalPages: Int!
  templates: [Template!]!
}

extend type Query {
  getTemplates(
    page: Int!
    limit: Int!
    topic: String
  ): TemplatePaginationResponse!
  getSavedTemplates(page: Int!, limit: Int!): SavedTemplatePaginationResponse!
}

extend type Mutation {
  filledTemplate(input: FilledTemplateRequestInput!): Response!
}

input AnswersInput {
  key: String!
  value: String!
}

input FilledTemplateRequestInput {
  templateId: ID!
  answers: [AnswersInput!]!
}

type SavedTemplatesData {
  id: ID!
  templateId: ID!
  title: String!
  topic: String!
  template: String!
  answers: [AnswersData!]!
}

type AnswersData {
  key: String!
  value: String!
}

type SavedTemplatePaginationResponse {
  total: Int!
  perPage: Int!
  currentPage: Int!
  totalPages: Int!
  savedTemplates: [SavedTemplatesData!]!
}
