extend type Mutation {
  templatePlayWithFriends(
    input: TemplatePlayWithFriendsRequestInput!
  ): Response!
  addAnswer(input: AddAnswerRequestInput!, id: ID!): AddAnswerResponse!
}

input TemplatePlayWithFriendsRequestInput {
  friendIds: String!
  templateId: ID!
  answer: [Answer!]!
}

input AddAnswerRequestInput {
  sendAnswerUserId: ID!
  key: String!
  value: String!
}

input Answer {
  key: String!
  value: String!
}

extend type Query {
  getFriendTemplates(
    page: Int!
    limit: Int!
    friendId: String!
  ): FriendTemplatePaginationResponse!
  getFriendTemplatesDetail(id: ID!): FriendTemplateDetail!
}

type FriendTemplatePaginationResponse {
  total: Int!
  perPage: Int!
  currentPage: Int!
  totalPages: Int!
  friendTemplates: [FriendTemplates!]!
}

type FriendTemplateDetail {
  id: ID!
  title: String!
  category: String!
  template: String!
  answers: [FriendAnswers!]!
  status: String!
}

type AddAnswerResponse {
  status: Boolean!
  message: String!
}

type FriendTemplates {
  id: ID!
  template: String!
  category: String!
  title: String!
  answers: [FriendAnswers!]!
  status: String!
}

type FriendAnswers {
  id: ID!
  key: String!
  value: String!
}
