extend type Mutation {
  ownGame(input: OwnGameRequestInput!): Response!
}

input OwnGameRequestInput {
  categoryId: ID!
  friendIds: ID!
  gameName: String!
}

extend type Query {
  getTriva(page: Int!, limit: Int!): HostTriviaPaginationResponse!
  getTrivaDetail(id: ID!): TriviaDetail!
  getAnsweredTrivia(page: Int!, limit: Int!): AnsweredTriviaPaginationResponse!
  getRequestedTrivia: [RequestedTrivia!]!
  AcceptRejectTrivia(id: ID!, status: String!): Response!
  addTriviaAnswer(id: ID!, answer: String!, role: String!): Response!
  getAllCategory(search: String!): [GetAllCategories!]!
}

type HostTriviaPaginationResponse {
  total: Int!
  perPage: Int!
  currentPage: Int!
  totalPages: Int!
  trivias: [TriviaListing!]!
}

type AnsweredTriviaPaginationResponse {
  total: Int!
  perPage: Int!
  currentPage: Int!
  totalPages: Int!
  trivias: [AnsweredTrivia!]!
}

type TriviaListing {
  id: ID!
  categoryName: String!
  gameName: String!
  status: String!
  role: String!
}

type AnsweredTrivia {
  id: ID!
  categoryName: String!
  gameName: String!
  status: String!
  role: String!
}

type RequestedTrivia {
  id: ID!
  user: UserInfo!
  status: String!
}

type UserInfo {
  id: ID!
  name: String!
  image: String!
}

type TriviaDetail {
  id: ID!
  question: String!
  answers: [String!]!
  answeredUsers: [Users!]!
  notAnsweredUsers: [Users!]!
  dareForWrongAnswer: String
  status: String!
  correctAnswer: String
}

type Users {
  id: ID!
  name: String!
  image: String!
  answer: String
  isCorrectAnswer: Boolean
}
