package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"laughifi/graph/model"
	"laughifi/handlers/admin/dashboard"
)

// GetDashboardData is the resolver for the getDashboardData field.
func (r *queryResolver) GetDashboardData(ctx context.Context) (*model.GetDashboardData, error) {
	getDahboardData, err := dashboard.GetDashboardCounts(ctx, r.DB)
	if err != nil {
		return nil, err
	}
	return getDahboardData, nil
}
