package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"laughifi/graph/model"
	"laughifi/handlers/admin/trivia"
)

// AddTrivia is the resolver for the addTrivia field.
func (r *mutationResolver) AddTrivia(ctx context.Context, input model.TriviaRequestInput) (*model.Response, error) {
	payload, err := trivia.AddTrivia(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return payload, nil
}

// EditTrivia is the resolver for the editTrivia field.
func (r *mutationResolver) EditTrivia(ctx context.Context, id string, input model.EditTriviaRequestInput) (*model.Response, error) {
	payload, err := trivia.EditTrivia(ctx, r.DB, id, input)
	if err != nil {
		return nil, err
	}
	return payload, nil
}

// DeleteTrivia is the resolver for the deleteTrivia field.
func (r *mutationResolver) DeleteTrivia(ctx context.Context, id string) (*model.Response, error) {
	payload, err := trivia.DeleteTrivia(ctx, r.DB, id)
	if err != nil {
		return nil, err
	}
	return payload, nil
}

// GetTrivias is the resolver for the getTrivias field.
func (r *queryResolver) GetTrivias(ctx context.Context, page int, limit int, search *string) (*model.TriviaPaginationResponse, error) {
	payload, err := trivia.GetTrivias(ctx, r.DB, page, limit, *search)
	if err != nil {
		return nil, err
	}
	return payload, nil
}

// GetTrivia is the resolver for the getTrivia field.
func (r *queryResolver) GetTrivia(ctx context.Context, id string) (*model.TriviaData, error) {
	payload, err := trivia.GetAdminTrivia(ctx, r.DB, id)
	if err != nil {
		return nil, err
	}
	return payload, nil
}
