package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"laughifi/graph/model"
	"laughifi/handlers/admin/templates"
)

// AdminTemplate is the resolver for the adminTemplate field.
func (r *mutationResolver) AdminTemplate(ctx context.Context, input model.AdminTemplateRequestInput) (*model.Response, error) {
	addTemplateData, err := templates.AddTemplate(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return addTemplateData, nil
}

// EditAdminTemplate is the resolver for the editAdminTemplate field.
func (r *mutationResolver) EditAdminTemplate(ctx context.Context, id string, input model.EditAdminTemplateRequestInput) (*model.Response, error) {
	editTemplateData, err := templates.EditTemplate(ctx, r.DB, id, input)
	if err != nil {
		return nil, err
	}
	return editTemplateData, nil
}

// DeleteAdminTemplate is the resolver for the deleteAdminTemplate field.
func (r *mutationResolver) DeleteAdminTemplate(ctx context.Context, id string) (*model.Response, error) {
	editTemplateData, err := templates.DeletedTemplateData(ctx, r.DB, id)
	if err != nil {
		return nil, err
	}
	return editTemplateData, nil
}

// GetAdminTemplates is the resolver for the getAdminTemplates field.
func (r *queryResolver) GetAdminTemplates(ctx context.Context, page int, limit int, search *string) (*model.AdminTemplatePaginationResponse, error) {
	getTemplatesData, err := templates.GetAllTemplates(ctx, r.DB, page, limit, *search)
	if err != nil {
		return nil, err
	}
	return getTemplatesData, nil
}

// GetAdminTemplate is the resolver for the getAdminTemplate field.
func (r *queryResolver) GetAdminTemplate(ctx context.Context, id string) (*model.AdminTemplate, error) {
	getTemplateData, err := templates.GetTemplateData(ctx, r.DB, id)
	if err != nil {
		return nil, err
	}
	return getTemplateData, nil
}

// GetAllCategories is the resolver for the getAllCategories field.
func (r *queryResolver) GetAllCategories(ctx context.Context) ([]*model.GetAllCategories, error) {
	getCategoriesData, err := templates.GetAllCategories(ctx, r.DB)
	if err != nil {
		return nil, err
	}
	return getCategoriesData, nil
}
