package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"laughifi/graph/model"
	"laughifi/handlers/admin/auth"
)

// AdminLogin is the resolver for the adminLogin field.
func (r *mutationResolver) AdminLogin(ctx context.Context, input model.AdminLoginRequestInput) (*model.AdminLoginResponse, error) {
	loginPayload, err := auth.LoginAdmin(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return loginPayload, nil
}

// AdminForgotPassword is the resolver for the adminForgotPassword field.
func (r *mutationResolver) AdminForgotPassword(ctx context.Context, input model.ForgotPasswordRequestInput) (*model.Response, error) {
	forgotPasswordPayload, err := auth.AdminForgotPassword(ctx, r.DB, r.SESClient, input)
	if err != nil {
		return nil, err
	}
	return forgotPasswordPayload, nil
}

// AdminVerifyOtpForResetPassword is the resolver for the adminVerifyOtpForResetPassword field.
func (r *mutationResolver) AdminVerifyOtpForResetPassword(ctx context.Context, input model.VerifyOtpForResetPasswordRequestInput) (*model.Response, error) {
	verifyOtpPayload, err := auth.AdminVerifyOtpForResetPassword(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return verifyOtpPayload, nil
}

// AdminResetPassword is the resolver for the adminResetPassword field.
func (r *mutationResolver) AdminResetPassword(ctx context.Context, input model.ResetPasswordRequestInput) (*model.Response, error) {
	resetPasswordPayload, err := auth.AdminResetPassword(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return resetPasswordPayload, nil
}

// AdminChangePassword is the resolver for the adminChangePassword field.
func (r *mutationResolver) AdminChangePassword(ctx context.Context, input model.ChangePasswordRequestInput) (*model.Response, error) {
	changePasswordPayload, err := auth.AdminChangePassword(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return changePasswordPayload, nil
}

// AdminEditProfile is the resolver for the adminEditProfile field.
func (r *mutationResolver) AdminEditProfile(ctx context.Context, input model.AdminEditProfileRequestInput) (*model.Response, error) {
	editUserData, err := auth.AdminEditAdmin(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return editUserData, nil
}

// Admin is the resolver for the admin field.
func (r *queryResolver) Admin(ctx context.Context) (*model.AdminLoginResponse, error) {
	getUserData, err := auth.GetAdminData(ctx, r.DB)
	if err != nil {
		return nil, err
	}
	return getUserData, nil
}
