package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"laughifi/graph/model"
	"laughifi/handlers/auth"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginRequestInput) (*model.LoginResponse, error) {
	loginPayload, err := auth.LoginCustomer(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return loginPayload, nil
}

// SocialLogin is the resolver for the socialLogin field.
func (r *mutationResolver) SocialLogin(ctx context.Context, input model.SocialLoginRequestInput) (*model.LoginResponse, error) {
	socialLoginPayload, err := auth.SocialLoginCustomer(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return socialLoginPayload, nil
}

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, input model.SignUpRequestInput) (*model.Response, error) {
	signupPayload, err := auth.Signup(ctx, r.DB, r.SESClient, input)
	if err != nil {
		return nil, err
	}
	return signupPayload, nil
}

// VerifyOtpForSignup is the resolver for the verifyOtpForSignup field.
func (r *mutationResolver) VerifyOtpForSignup(ctx context.Context, input model.VerifyOtpForSignUpRequestInput) (*model.LoginResponse, error) {
	verifyOtpForSignupPayload, err := auth.VerifyOtpForSignup(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return verifyOtpForSignupPayload, nil
}

// ForgotPassword is the resolver for the forgotPassword field.
func (r *mutationResolver) ForgotPassword(ctx context.Context, input model.ForgotPasswordRequestInput) (*model.Response, error) {
	ForgotPasswordPayload, err := auth.ForgotPassword(ctx, r.DB, r.SESClient, input)
	if err != nil {
		return nil, err
	}
	return ForgotPasswordPayload, nil
}

// VerifyOtpForResetPassword is the resolver for the verifyOtpForResetPassword field.
func (r *mutationResolver) VerifyOtpForResetPassword(ctx context.Context, input model.VerifyOtpForResetPasswordRequestInput) (*model.Response, error) {
	VerifyOtpPayload, err := auth.VerifyOtpForResetPassword(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return VerifyOtpPayload, nil
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, input model.ResetPasswordRequestInput) (*model.Response, error) {
	resetPasswordPayload, err := auth.ResetPassword(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return resetPasswordPayload, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
