package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"laughifi/graph/model"
	category "laughifi/handlers/admin/categories"
)

// Category is the resolver for the category field.
func (r *mutationResolver) Category(ctx context.Context, input model.CategoryRequestInput) (*model.Response, error) {
	addCategoryData, err := category.AddCatgeory(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return addCategoryData, nil
}

// EditCategory is the resolver for the editCategory field.
func (r *mutationResolver) EditCategory(ctx context.Context, id string, input model.EditCategoryRequestInput) (*model.Response, error) {
	editCategoryData, err := category.EditCategory(ctx, r.DB, id, input)
	if err != nil {
		return nil, err
	}
	return editCategoryData, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (*model.Response, error) {
	deleteCategoryData, err := category.DeletedCategoryData(ctx, r.DB, id)
	if err != nil {
		return nil, err
	}
	return deleteCategoryData, nil
}

// GetCategories is the resolver for the getCategories field.
func (r *queryResolver) GetCategories(ctx context.Context, page int, limit int, search *string) (*model.CategoriesPaginationResponse, error) {
	deleteCategoryData, err := category.GetCategories(ctx, r.DB, page, limit, *search)
	if err != nil {
		return nil, err
	}
	return deleteCategoryData, nil
}

// GetCategory is the resolver for the getCategory field.
func (r *queryResolver) GetCategory(ctx context.Context, id string) (*model.Category, error) {
	getCategoryData, err := category.GetCategoryData(ctx, r.DB, id)
	if err != nil {
		return nil, err
	}
	return getCategoryData, nil
}
