package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"
	"laughifi/graph/model"
	"laughifi/handlers/user/friends"
)

// UpdateStatus is the resolver for the updateStatus field.
func (r *mutationResolver) UpdateStatus(ctx context.Context, userID string, input model.UpdateStatusRequestInput) (*model.Response, error) {
	status, err := friends.AcceptRejectRequest(ctx, r.DB, userID, input)
	if err != nil {
		return nil, err
	}
	return status, nil
}

// SendFriendRequest is the resolver for the sendFriendRequest field.
func (r *mutationResolver) SendFriendRequest(ctx context.Context, input model.SendFriendRequestInput) (*model.RequestResponse, error) {
	friends, err := friends.SendFriendRequest(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return friends, nil
}

// CancelFriendRequest is the resolver for the cancelFriendRequest field.
func (r *mutationResolver) CancelFriendRequest(ctx context.Context, input model.SendFriendRequestInput) (*model.Response, error) {
	friends, err := friends.CancelFriendRequest(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return friends, nil
}

// GetLaughifiUsers is the resolver for the getLaughifiUsers field.
func (r *queryResolver) GetLaughifiUsers(ctx context.Context, page int, limit int, search *string) (*model.LaughifiUserPaginationResponse, error) {
	friends, err := friends.GetLaughifiCustomers(ctx, r.DB, page, limit, *search)
	if err != nil {
		return nil, err
	}
	return friends, nil
}

// GetFriends is the resolver for the getFriends field.
func (r *queryResolver) GetFriends(ctx context.Context, page int, limit int, search *string) (*model.FriendPaginationResponse, error) {
	friends, err := friends.GetFriends(ctx, r.DB, page, limit, *search)
	if err != nil {
		return nil, err
	}
	return friends, nil
}

// GetFriendsRequests is the resolver for the getFriendsRequests field.
func (r *queryResolver) GetFriendsRequests(ctx context.Context) ([]*model.Friend, error) {
	friends, err := friends.GetFriendRequests(ctx, r.DB)
	if err != nil {
		return nil, err
	}
	return friends, nil
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *mutationResolver) SubscriptionConnection(ctx context.Context, input model.SubscriptionRequestInput) (*model.Response, error) {
	panic(fmt.Errorf("not implemented: SubscriptionConnection - subscriptionConnection"))
}
