package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"laughifi/graph/model"
	"laughifi/handlers/user/friends"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// UpdateStatus is the resolver for the updateStatus field.
func (r *mutationResolver) UpdateStatus(ctx context.Context, userID string, input model.UpdateStatusRequestInput) (*model.Response, error) {
	status, err := friends.AcceptRejectRequest(ctx, r.DB, userID, input)
	if err != nil {
		return nil, err
	}
	return status, nil
}

// SendFriendRequest is the resolver for the sendFriendRequest field.
func (r *mutationResolver) SendFriendRequest(ctx context.Context, input model.SendFriendRequestInput) (*model.Response, error) {
	friends, err := friends.SendFriendRequest(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return friends, nil
}

// GetLaughifiUsers is the resolver for the getLaughifiUsers field.
func (r *queryResolver) GetLaughifiUsers(ctx context.Context, page int, limit int, search *string) (*model.LaughifiUserPaginationResponse, error) {
	friends, err := friends.GetLaughifiCustomers(ctx, r.DB, page, limit, *search)
	if err != nil {
		return nil, gqlerror.Errorf("failed: %v", err)
	}
	return friends, nil
}

// GetFriends is the resolver for the getFriends field.
func (r *queryResolver) GetFriends(ctx context.Context, page int, limit int) (*model.FriendPaginationResponse, error) {
	friends, err := friends.GetFriends(ctx, r.DB, page, limit)
	if err != nil {
		return nil, err
	}
	return friends, nil
}

// GetFriendsRequests is the resolver for the getFriendsRequests field.
func (r *queryResolver) GetFriendsRequests(ctx context.Context) ([]*model.Friend, error) {
	friends, err := friends.GetFriendRequests(ctx, r.DB)
	if err != nil {
		return nil, err
	}
	return friends, nil
}
