package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"laughifi/graph/model"
	"laughifi/handlers/auth"
)

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input model.ChangePasswordRequestInput) (*model.Response, error) {
	changePasswordPayload, err := auth.ChangePassword(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return changePasswordPayload, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) (*model.LoginResponse, error) {
	getUserData, err := auth.GetUserData(ctx, r.DB)
	if err != nil {
		return nil, err
	}
	return getUserData, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
