package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"laughifi/graph/model"
	"laughifi/handlers/user/templates"
)

// TemplatePlayWithFriends is the resolver for the templatePlayWithFriends field.
func (r *mutationResolver) TemplatePlayWithFriends(ctx context.Context, input model.TemplatePlayWithFriendsRequestInput) (*model.Response, error) {
	templates, err := templates.TemplatePlayWithFriends(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return templates, nil
}

// AddAnswer is the resolver for the addAnswer field.
func (r *mutationResolver) AddAnswer(ctx context.Context, input model.AddAnswerRequestInput, id string) (*model.AddAnswerResponse, error) {
	templates, err := templates.AddAnswer(ctx, r.DB, input, id)
	if err != nil {
		return nil, err
	}
	return templates, nil
}

// GetFriendTemplates is the resolver for the getFriendTemplates field.
func (r *queryResolver) GetFriendTemplates(ctx context.Context, page int, limit int, friendID string) (*model.FriendTemplatePaginationResponse, error) {
	templates, err := templates.GetFriendTemplates(ctx, r.DB, page, limit, friendID)
	if err != nil {
		return nil, err
	}
	return templates, nil
}
