package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"laughifi/graph/model"
	"laughifi/handlers/templates"
)

// GetTemplates is the resolver for the getTemplates field.
func (r *queryResolver) GetTemplates(ctx context.Context, page int, limit int, topic *string) (*model.TemplatePaginationResponse, error) {
	templates, err := templates.GetTemplates(ctx, r.DB, page, limit, *topic)
	if err != nil {
		return nil, err
	}
	return templates, nil
}
