package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"
	"laughifi/graph/model"
	"laughifi/handlers/user/templates"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// TemplatePlayWithFriends is the resolver for the templatePlayWithFriends field.
func (r *mutationResolver) TemplatePlayWithFriends(ctx context.Context, input model.TemplatePlayWithFriendsRequestInput) (*model.Response, error) {
	templates, err := templates.TemplatePlayWithFriends(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return templates, nil
}

// AddAnswer is the resolver for the addAnswer field.
func (r *mutationResolver) AddAnswer(ctx context.Context, input model.AddAnswerRequestInput, id string) (*model.AddAnswerResponse, error) {
	templates, err := templates.AddAnswer(ctx, r.DB, input, id)
	if err != nil {
		return nil, err
	}
	return templates, nil
}

// GetFriendTemplates is the resolver for the getFriendTemplates field.
func (r *queryResolver) GetFriendTemplates(ctx context.Context, page int, limit int, friendID string) (*model.FriendTemplatePaginationResponse, error) {
	templates, err := templates.GetFriendTemplates(ctx, r.DB, page, limit, friendID)
	if err != nil {
		return nil, err
	}
	return templates, nil
}

// TemplateShared is the resolver for the templateShared field.
func (r *subscriptionResolver) TemplateShared(ctx context.Context, userID string) (<-chan *model.TemplatePlayWithFriend, error) {
	if r.SubscriptionMgr == nil {
		return nil, gqlerror.Errorf("Subscription manager is not initialized")
	}

	messageChan := make(chan *model.TemplatePlayWithFriend, 1)

	fmt.Println("Adding subscriber with ID:", userID)
	r.SubscriptionMgr.AddSubscriber(userID, messageChan)

	go func() {
		<-ctx.Done()
		r.SubscriptionMgr.RemoveSubscriber(userID)
	}()

	return messageChan, nil
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
