package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"laughifi/graph/model"
	"laughifi/handlers/user/templates"
)

// FilledTemplate is the resolver for the filledTemplate field.
func (r *mutationResolver) FilledTemplate(ctx context.Context, input model.FilledTemplateRequestInput) (*model.Response, error) {
	filledTemplates, err := templates.FilledTemplates(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return filledTemplates, nil
}

// GetTemplates is the resolver for the getTemplates field.
func (r *queryResolver) GetTemplates(ctx context.Context, page int, limit int, category *string) (*model.TemplatePaginationResponse, error) {
	templates, err := templates.GetTemplates(ctx, r.DB, page, limit, *category)
	if err != nil {
		return nil, err
	}
	return templates, nil
}

// GetSavedTemplates is the resolver for the getSavedTemplates field.
func (r *queryResolver) GetSavedTemplates(ctx context.Context, page int, limit int) (*model.SavedTemplatePaginationResponse, error) {
	getFilledTemplates, err := templates.GetFilledTemplates(ctx, r.DB, page, limit)
	if err != nil {
		return nil, err
	}
	return getFilledTemplates, nil
}
