package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"
	"laughifi/graph/model"
	"laughifi/handlers/user/trivia"
)

// OwnGame is the resolver for the ownGame field.
func (r *mutationResolver) OwnGame(ctx context.Context, input model.OwnGameRequestInput) (*model.Response, error) {
	payload, err := trivia.OwnGame(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return payload, nil
}

// GetTriva is the resolver for the getTriva field.
func (r *queryResolver) GetTriva(ctx context.Context) ([]*model.TriviaListing, error) {
	payload, err := trivia.GetTrivia(ctx, r.DB)
	if err != nil {
		return nil, err
	}
	return payload, nil
}

// GetTrivaDetail is the resolver for the getTrivaDetail field.
func (r *queryResolver) GetTrivaDetail(ctx context.Context, id string) (*model.TriviaDetail, error) {
	payload, err := trivia.GetTriviaDetail(ctx, r.DB, id)
	if err != nil {
		return nil, err
	}
	return payload, nil
}

// GetAnsweredTrivia is the resolver for the getAnsweredTrivia field.
func (r *queryResolver) GetAnsweredTrivia(ctx context.Context) ([]*model.AnsweredTrivia, error) {
	payload, err := trivia.GetAnsweredTrivia(ctx, r.DB)
	if err != nil {
		return nil, err
	}
	return payload, nil
}

// GetRequestedTrivia is the resolver for the getRequestedTrivia field.
func (r *queryResolver) GetRequestedTrivia(ctx context.Context) ([]*model.RequestedTrivia, error) {
	payload, err := trivia.GetRequestedTrivia(ctx, r.DB)
	if err != nil {
		return nil, err
	}
	return payload, nil
}

// AcceptRejectTrivia is the resolver for the AcceptRejectTrivia field.
func (r *queryResolver) AcceptRejectTrivia(ctx context.Context, id string, status string) (*model.Response, error) {
	payload, err := trivia.AcceptRejectTrivia(ctx, r.DB, id, status)
	if err != nil {
		return nil, err
	}
	return payload, nil
}

// AddTriviaAnswer is the resolver for the addTriviaAnswer field.
func (r *queryResolver) AddTriviaAnswer(ctx context.Context, id string, answer string) (*model.Response, error) {
	payload, err := trivia.AddTriviaAnswer(ctx, r.DB, id, answer)
	if err != nil {
		return nil, err
	}
	return payload, nil
}

// GetAllCategory is the resolver for the getAllCategory field.
func (r *queryResolver) GetAllCategory(ctx context.Context) ([]*model.GetAllCategories, error) {
	panic(fmt.Errorf("not implemented: GetAllCategory - getAllCategory"))
}
