package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"laughifi/graph/model"
	wouldyourather "laughifi/handlers/user/wouldYouRather"
)

// FilledWouldYouRather is the resolver for the filledWouldYouRather field.
func (r *mutationResolver) FilledWouldYouRather(ctx context.Context, input model.FilledWouldYouRatherRequestInput) (*model.Response, error) {
	filledWouldYouRather, err := wouldyourather.FilledWouldYouRather(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return filledWouldYouRather, nil
}

// GetAllWouldYouRathers is the resolver for the getAllWouldYouRathers field.
func (r *queryResolver) GetAllWouldYouRathers(ctx context.Context, page int, limit int) (*model.WouldYouRatherPaginationResp, error) {
	wouldYouRathers, err := wouldyourather.GetWouldYouRathers(ctx, r.DB, page, limit)
	if err != nil {
		return nil, err
	}
	return wouldYouRathers, nil
}

// GetSavedWouldYouRathers is the resolver for the getSavedWouldYouRathers field.
func (r *queryResolver) GetSavedWouldYouRathers(ctx context.Context, page int, limit int) (*model.SavedWouldYouRatherPaginationResp, error) {
	filledWouldRathers, err := wouldyourather.GetFilledWouldRathers(ctx, r.DB, page, limit)
	if err != nil {
		return nil, err
	}
	return filledWouldRathers, nil
}
