package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"laughifi/graph/model"
	wouldyourather "laughifi/handlers/admin/wouldYouRather"
)

// WouldYouRather is the resolver for the wouldYouRather field.
func (r *mutationResolver) WouldYouRather(ctx context.Context, input model.WouldYouRatherRequestInput) (*model.Response, error) {
	addWouldYouRatherData, err := wouldyourather.AddWouldYouRather(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return addWouldYouRatherData, nil
}

// EditWouldYouRather is the resolver for the editWouldYouRather field.
func (r *mutationResolver) EditWouldYouRather(ctx context.Context, id string, input model.EditWouldYouRatherRequestInput) (*model.Response, error) {
	editWouldYouRatherData, err := wouldyourather.EditWouldYouRather(ctx, r.DB, id, input)
	if err != nil {
		return nil, err
	}
	return editWouldYouRatherData, nil
}

// DeleteWouldYouRather is the resolver for the deleteWouldYouRather field.
func (r *mutationResolver) DeleteWouldYouRather(ctx context.Context, id string) (*model.Response, error) {
	deleteWouldYouRatherData, err := wouldyourather.DeleteWouldYouRather(ctx, r.DB, id)
	if err != nil {
		return nil, err
	}
	return deleteWouldYouRatherData, nil
}

// GetWouldYouRathers is the resolver for the getWouldYouRathers field.
func (r *queryResolver) GetWouldYouRathers(ctx context.Context, page int, limit int, search *string) (*model.WouldYouRathersPaginationResponse, error) {
	geWouldYouRathersData, err := wouldyourather.GetWouldYouRathers(ctx, r.DB, page, limit, *search)
	if err != nil {
		return nil, err
	}
	return geWouldYouRathersData, nil
}

// GetWouldYouRather is the resolver for the getWouldYouRather field.
func (r *queryResolver) GetWouldYouRather(ctx context.Context, id string) (*model.WouldYouRathersDetail, error) {
	geWouldYouRatherData, err := wouldyourather.GetWouldYouRatherData(ctx, r.DB, id)
	if err != nil {
		return nil, err
	}
	return geWouldYouRatherData, nil
}
