// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type AdminEditProfileRequestInput struct {
	FirstName           string          `json:"firstName"`
	LastName            string          `json:"lastName"`
	OldProfileImageURL  string          `json:"oldProfileImageUrl"`
	NewProfileImageFile *graphql.Upload `json:"newProfileImageFile,omitempty"`
}

type AdminLoginRequestInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type AdminLoginResponse struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Image     string `json:"image"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	Token     string `json:"token"`
}

type AnswersData struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type AnswersInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type CategoriesPaginationResponse struct {
	Total       int         `json:"total"`
	PerPage     int         `json:"perPage"`
	CurrentPage int         `json:"currentPage"`
	TotalPages  int         `json:"totalPages"`
	Categories  []*Category `json:"categories"`
}

type Category struct {
	ID       string `json:"id"`
	Category string `json:"category"`
}

type CategoryRequestInput struct {
	Category string `json:"category"`
}

type ChangePasswordRequestInput struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
	ConfirmPassword string `json:"confirmPassword"`
}

type EditCategoryRequestInput struct {
	Category string `json:"category"`
}

type EditProfileRequestInput struct {
	Name                string          `json:"name"`
	OldProfileImageURL  string          `json:"oldProfileImageUrl"`
	NewProfileImageFile *graphql.Upload `json:"newProfileImageFile,omitempty"`
}

type FilledTemplateRequestInput struct {
	TemplateID string          `json:"templateId"`
	Answers    []*AnswersInput `json:"answers"`
}

type ForgotPasswordRequestInput struct {
	Email string `json:"email"`
}

type Friend struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Image string `json:"image"`
}

type FriendPaginationResponse struct {
	Total       int       `json:"total"`
	PerPage     int       `json:"perPage"`
	CurrentPage int       `json:"currentPage"`
	TotalPages  int       `json:"totalPages"`
	Friends     []*Friend `json:"friends"`
}

type LaughifiUserPaginationResponse struct {
	Total       int       `json:"total"`
	PerPage     int       `json:"perPage"`
	CurrentPage int       `json:"currentPage"`
	TotalPages  int       `json:"totalPages"`
	Users       []*Friend `json:"users"`
}

type LoginRequestInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	Image       string `json:"image"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
	HasPassword bool   `json:"hasPassword"`
	Token       string `json:"token"`
}

type Mutation struct {
}

type Query struct {
}

type ResendOtpRequestInput struct {
	Email string `json:"email"`
}

type ResetPasswordRequestInput struct {
	Email           string `json:"email"`
	NewPassword     string `json:"newPassword"`
	ConfirmPassword string `json:"confirmPassword"`
}

type Response struct {
	Message string `json:"message"`
}

type SavedTemplatePaginationResponse struct {
	Total          int                   `json:"total"`
	PerPage        int                   `json:"perPage"`
	CurrentPage    int                   `json:"currentPage"`
	TotalPages     int                   `json:"totalPages"`
	SavedTemplates []*SavedTemplatesData `json:"savedTemplates"`
}

type SavedTemplatesData struct {
	ID         string         `json:"id"`
	TemplateID string         `json:"templateId"`
	Title      string         `json:"title"`
	Topic      string         `json:"topic"`
	Template   string         `json:"template"`
	Answers    []*AnswersData `json:"answers"`
}

type SendFriendRequestInput struct {
	UserIds []string `json:"userIds"`
}

type SignUpRequestInput struct {
	Email string `json:"email"`
}

type SocialLoginRequestInput struct {
	SocialID string  `json:"socialId"`
	Type     string  `json:"type"`
	Email    *string `json:"email,omitempty"`
	Name     string  `json:"name"`
}

type Template struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Topic    string `json:"topic"`
	Template string `json:"template"`
}

type TemplatePaginationResponse struct {
	Total       int         `json:"total"`
	PerPage     int         `json:"perPage"`
	CurrentPage int         `json:"currentPage"`
	TotalPages  int         `json:"totalPages"`
	Templates   []*Template `json:"templates"`
}

type UpdateStatusRequestInput struct {
	Status string `json:"Status"`
}

type VerifyOtpForResetPasswordRequestInput struct {
	Email string `json:"email"`
	Otp   string `json:"otp"`
}

type VerifyOtpForSignUpRequestInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Otp      string `json:"otp"`
}
