// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type AddAnswerRequestInput struct {
	SendAnswerUserID string `json:"sendAnswerUserId"`
	Key              string `json:"key"`
	Value            string `json:"value"`
}

type AddAnswerResponse struct {
	Status  bool   `json:"status"`
	Message string `json:"message"`
}

type AdminEditProfileRequestInput struct {
	FirstName           string          `json:"firstName"`
	LastName            string          `json:"lastName"`
	OldProfileImageURL  string          `json:"oldProfileImageUrl"`
	NewProfileImageFile *graphql.Upload `json:"newProfileImageFile,omitempty"`
}

type AdminLoginRequestInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type AdminLoginResponse struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Image     string `json:"image"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	Token     string `json:"token"`
}

type AdminTemplate struct {
	ID       string `json:"id"`
	Category string `json:"category"`
	Title    string `json:"title"`
	Template string `json:"template"`
}

type AdminTemplatePaginationResponse struct {
	Total          int               `json:"total"`
	PerPage        int               `json:"perPage"`
	CurrentPage    int               `json:"currentPage"`
	TotalPages     int               `json:"totalPages"`
	AdminTemplates []*AdminTemplates `json:"adminTemplates"`
}

type AdminTemplateRequestInput struct {
	CategoryID string `json:"categoryId"`
	Title      string `json:"title"`
	Template   string `json:"template"`
}

type AdminTemplates struct {
	ID       string `json:"id"`
	Category string `json:"category"`
	Template string `json:"template"`
}

type Answer struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type AnsweredTrivia struct {
	ID           string `json:"id"`
	CategoryName string `json:"categoryName"`
	GameName     string `json:"gameName"`
	Status       string `json:"status"`
}

type AnswersData struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type AnswersInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type CategoriesPaginationResponse struct {
	Total       int         `json:"total"`
	PerPage     int         `json:"perPage"`
	CurrentPage int         `json:"currentPage"`
	TotalPages  int         `json:"totalPages"`
	Categories  []*Category `json:"categories"`
}

type Category struct {
	ID       string `json:"id"`
	Category string `json:"category"`
}

type CategoryRequestInput struct {
	Category string `json:"category"`
}

type ChangePasswordRequestInput struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
	ConfirmPassword string `json:"confirmPassword"`
}

type EditAdminTemplateRequestInput struct {
	CategoryID string `json:"categoryId"`
	Title      string `json:"title"`
	Template   string `json:"template"`
}

type EditCategoryRequestInput struct {
	Category string `json:"category"`
}

type EditProfileRequestInput struct {
	Name                string          `json:"name"`
	OldProfileImageURL  string          `json:"oldProfileImageUrl"`
	NewProfileImageFile *graphql.Upload `json:"newProfileImageFile,omitempty"`
}

type EditWouldYouRatherRequestInput struct {
	Question string   `json:"question"`
	Options  []string `json:"options"`
}

type FilledTemplateRequestInput struct {
	TemplateID string          `json:"templateId"`
	Answers    []*AnswersInput `json:"answers"`
}

type FilledWouldYouRatherRequestInput struct {
	WouldYouRatherID string `json:"wouldYouRatherId"`
	Answer           string `json:"answer"`
}

type ForgotPasswordRequestInput struct {
	Email string `json:"email"`
}

type Friend struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Image  string `json:"image"`
	Status bool   `json:"status"`
}

type FriendAnswers struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type FriendPaginationResponse struct {
	Total       int       `json:"total"`
	PerPage     int       `json:"perPage"`
	CurrentPage int       `json:"currentPage"`
	TotalPages  int       `json:"totalPages"`
	Friends     []*Friend `json:"friends"`
}

type FriendTemplateDetail struct {
	ID       string           `json:"id"`
	Title    string           `json:"title"`
	Category string           `json:"category"`
	Template string           `json:"template"`
	Answers  []*FriendAnswers `json:"answers"`
}

type FriendTemplatePaginationResponse struct {
	Total           int                `json:"total"`
	PerPage         int                `json:"perPage"`
	CurrentPage     int                `json:"currentPage"`
	TotalPages      int                `json:"totalPages"`
	FriendTemplates []*FriendTemplates `json:"friendTemplates"`
}

type FriendTemplates struct {
	ID       string           `json:"id"`
	Template string           `json:"template"`
	Category string           `json:"category"`
	Title    string           `json:"title"`
	Answers  []*FriendAnswers `json:"answers"`
	Status   string           `json:"status"`
}

type GetAllCategories struct {
	ID       string `json:"id"`
	Category string `json:"category"`
}

type GetDashboardData struct {
	TemplatesCount      int `json:"templatesCount"`
	WouldYouRatherCount int `json:"wouldYouRatherCount"`
	CategoryCount       int `json:"categoryCount"`
}

type LaughifiUserPaginationResponse struct {
	Total       int       `json:"total"`
	PerPage     int       `json:"perPage"`
	CurrentPage int       `json:"currentPage"`
	TotalPages  int       `json:"totalPages"`
	Users       []*Friend `json:"users"`
}

type LoginRequestInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	Image       string `json:"image"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
	HasPassword bool   `json:"hasPassword"`
	Token       string `json:"token"`
}

type Mutation struct {
}

type OwnGameRequestInput struct {
	CategoryID string `json:"categoryId"`
	FriendIds  string `json:"friendIds"`
	GameName   string `json:"gameName"`
}

type Query struct {
}

type RequestResponse struct {
	Message string `json:"message"`
}

type RequestedTrivia struct {
	ID     string    `json:"id"`
	User   *UserInfo `json:"user"`
	Status string    `json:"status"`
}

type ResendOtpRequestInput struct {
	Email string `json:"email"`
}

type ResetPasswordRequestInput struct {
	Email           string `json:"email"`
	NewPassword     string `json:"newPassword"`
	ConfirmPassword string `json:"confirmPassword"`
}

type Response struct {
	Message string `json:"message"`
}

type SavedTemplatePaginationResponse struct {
	Total          int                   `json:"total"`
	PerPage        int                   `json:"perPage"`
	CurrentPage    int                   `json:"currentPage"`
	TotalPages     int                   `json:"totalPages"`
	SavedTemplates []*SavedTemplatesData `json:"savedTemplates"`
}

type SavedTemplatesData struct {
	ID         string         `json:"id"`
	TemplateID string         `json:"templateId"`
	Title      string         `json:"title"`
	Category   string         `json:"category"`
	Template   string         `json:"template"`
	Answers    []*AnswersData `json:"answers"`
}

type SavedWouldYouRatherData struct {
	ID             string `json:"id"`
	WouldYouRather string `json:"wouldYouRather"`
	Answer         string `json:"answer"`
}

type SavedWouldYouRatherPaginationResp struct {
	Total                int                        `json:"total"`
	PerPage              int                        `json:"perPage"`
	CurrentPage          int                        `json:"currentPage"`
	TotalPages           int                        `json:"totalPages"`
	SavedWouldYouRathers []*SavedWouldYouRatherData `json:"savedWouldYouRathers"`
}

type SendFriendRequestInput struct {
	UserID string `json:"userId"`
}

type SignUpRequestInput struct {
	Email string `json:"email"`
}

type SocialLoginRequestInput struct {
	SocialID string  `json:"socialId"`
	Type     string  `json:"type"`
	Email    *string `json:"email,omitempty"`
	Name     string  `json:"name"`
}

type SubscriptionRequestInput struct {
	ID         string `json:"id"`
	Connection bool   `json:"connection"`
}

type Template struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Category string `json:"category"`
	Template string `json:"template"`
}

type TemplatePaginationResponse struct {
	Total       int         `json:"total"`
	PerPage     int         `json:"perPage"`
	CurrentPage int         `json:"currentPage"`
	TotalPages  int         `json:"totalPages"`
	Templates   []*Template `json:"templates"`
}

type TemplatePlayWithFriendsRequestInput struct {
	FriendIds  string    `json:"friendIds"`
	TemplateID string    `json:"templateId"`
	Answer     []*Answer `json:"answer"`
}

type TriviaDetail struct {
	ID                 string   `json:"id"`
	Question           string   `json:"question"`
	Answers            []string `json:"answers"`
	AnsweredUsers      []*Users `json:"answeredUsers"`
	NotAnsweredUsers   []*Users `json:"notAnsweredUsers"`
	DareForWrongAnswer *string  `json:"dareForWrongAnswer,omitempty"`
}

type TriviaListing struct {
	ID           string `json:"id"`
	CategoryName string `json:"categoryName"`
	GameName     string `json:"gameName"`
	Status       string `json:"status"`
}

type UpdateStatusRequestInput struct {
	Status string `json:"Status"`
}

type UserInfo struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Image string `json:"image"`
}

type Users struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	Image           string  `json:"image"`
	Answer          *string `json:"answer,omitempty"`
	IsCorrectAnswer *bool   `json:"isCorrectAnswer,omitempty"`
}

type VerifyOtpForResetPasswordRequestInput struct {
	Email string `json:"email"`
	Otp   string `json:"otp"`
}

type VerifyOtpForSignUpRequestInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Otp      string `json:"otp"`
}

type WouldYouRatherData struct {
	ID             string   `json:"id"`
	WouldYouRather string   `json:"wouldYouRather"`
	Options        []string `json:"options"`
}

type WouldYouRatherPaginationResp struct {
	Total           int                   `json:"total"`
	PerPage         int                   `json:"perPage"`
	CurrentPage     int                   `json:"currentPage"`
	TotalPages      int                   `json:"totalPages"`
	WouldYouRathers []*WouldYouRatherData `json:"wouldYouRathers"`
}

type WouldYouRatherRequestInput struct {
	Question string   `json:"question"`
	Options  []string `json:"options"`
}

type WouldYouRathers struct {
	ID       string `json:"id"`
	Question string `json:"question"`
}

type WouldYouRathersDetail struct {
	ID       string   `json:"id"`
	Question string   `json:"question"`
	Options  []string `json:"options"`
}

type WouldYouRathersPaginationResponse struct {
	Total           int                `json:"total"`
	PerPage         int                `json:"perPage"`
	CurrentPage     int                `json:"currentPage"`
	TotalPages      int                `json:"totalPages"`
	WouldYouRathers []*WouldYouRathers `json:"wouldYouRathers"`
}
